[project]
name = "cbrkit-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cbrkit>=0.28.5",
    "cbrkit[nlp]>=0.28.5",
    "notebook>=7.4.7",
]
